# Site settings
title: Yellowblue - Responsive Jekyll Theme
email: info@yellowblue.eu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog-try/" # the subpath of your site, e.g. /blog/
url: "https://david-zhang-blog.github.io" # the base hostname & protocol for your site
twitter_username: #
github_username: david-zhang-blog

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude: ['node_modules', 'Gruntfile.js', 'package.json']

highlighter: rouge

gems:
   - jekyll-paginate

# YB Settings
excerpt_separator: <!-- more -->
paginate: 4
comments: false
